<STYLE type="text/css">
.whiteUnderlined {
	FONT-WEIGHT: bold;
	FONT-SIZE: 11px;
	COLOR: #ffffff;
	FONT-FAMILY: Arial, Helvetica, sans-serif;
	HEIGHT: 14px;
	TEXT-DECORATION: underline
}

.goButton {
	BORDER-RIGHT: 0px;
	BORDER-TOP: 0px;
	BACKGROUND: url(${imgdir}/go.gif) #f5c5c1 fixed no-repeat center center;
	BORDER-LEFT: 0px;
	WIDTH: 16px;
	BORDER-BOTTOM: 0px;
	HEIGHT: 14px
}

.inputField {
	FONT-SIZE: 10px;
	COLOR: #000000;
	FONT-FAMILY: Arial, Helvetica, sans-serif;
	HEIGHT: 16px
}

.titles {
	FONT-WEIGHT: bold;
	FONT-SIZE: 14px;
	COLOR: #2981b2;
	FONT-FAMILY: Arial, Helvetica, sans-serif
}

.blackSubtitles {
	FONT-WEIGHT: bold;
	FONT-SIZE: 10px;
	COLOR: #000000;
	FONT-FAMILY: Arial, Helvetica, sans-serif;
	TEXT-DECORATION: underline
}

.text {
	FONT-SIZE: 10px;
	COLOR: #000000;
	FONT-FAMILY: Arial, Helvetica, sans-serif
}

.greySubtitles {
	FONT-SIZE: 10px;
	COLOR: #9f9e9e;
	FONT-FAMILY: Arial, Helvetica, sans-serif;
	TEXT-DECORATION: underline
}

.subscribe {
	FONT-WEIGHT: bold;
	FONT-SIZE: 12px;
	COLOR: #2981b2;
	FONT-FAMILY: Arial, Helvetica, sans-serif;
	TEXT-DECORATION: underline
}

.textBlack {
	FONT-WEIGHT: bold;
	FONT-SIZE: 12px;
	COLOR: #000000;
	FONT-FAMILY: Arial, Helvetica, sans-serif
}

.blueBorderLight {
	BORDER-RIGHT: #a0ccde 2px solid;
	BORDER-TOP: #a0ccde 2px solid;
	BORDER-LEFT: #a0ccde 2px solid;
	BORDER-BOTTOM: #a0ccde 2px solid
}

.blackBorder {
	BORDER-RIGHT: #000000 1px solid;
	BORDER-TOP: #000000 1px solid;
	BORDER-LEFT: #000000 1px solid;
	BORDER-BOTTOM: #000000 1px solid
}

.blackUnderlined {
	FONT-SIZE: 10px;
	COLOR: #000000;
	FONT-FAMILY: Arial, Helvetica, sans-serif;
	TEXT-DECORATION: underline
}

.fundoRiscas {
	BACKGROUND-IMAGE: url(${imgdir}/fundoRiscas.gif);
	BACKGROUND-REPEAT: repeat
}

.titleRed {
	FONT-WEIGHT: bold;
	FONT-SIZE: 15px;
	COLOR: #ed1b23;
	LINE-HEIGHT: 14px;
	FONT-FAMILY: Arial, Helvetica, sans-serif
}

.PixelBlue {
	BACKGROUND-IMAGE: url(${imgdir}/pixel-bleu.jpg);
	LINE-HEIGHT: 14px;
	BACKGROUND-REPEAT: repeat-x
}

.titleBlue {
	BACKGROUND-POSITION: right top;
	BACKGROUND-IMAGE: url(${imgdir}/barraTituloCantoDir.jpg);
	LINE-HEIGHT: 14px;
	BACKGROUND-REPEAT: no-repeat
}

.titleBlueTexto {
	FONT-WEIGHT: bold;
	FONT-SIZE: 15px;
	COLOR: #5b9ec4;
	FONT-FAMILY: Arial, Helvetica, sans-serif
}

.subtitleRed {
	FONT-WEIGHT: bold;
	FONT-SIZE: 14px;
	COLOR: #ed1b23;
	TEXT-ALIGN: LEFT !important;
	FONT-FAMILY: Arial, Helvetica, sans-serif
}

.textRed {
	FONT-SIZE: 10px;
	COLOR: #ed1b23;
	FONT-FAMILY: Arial, Helvetica, sans-serif
}

.borderGreyHorizontal {
	BACKGROUND-IMAGE: url(${imgdir}/borderGreyDot.gif);
	BACKGROUND-REPEAT: repeat-x
}

.borderGreyVertical {
	BACKGROUND-IMAGE: url(${imgdir}/borderGreyDot.gif);
	BACKGROUND-REPEAT: repeat-y
}

.borderGreyHorizontalBottom {
	BACKGROUND-IMAGE: url(${imgdir}/borderGreyLineHorizontal.gif);
	BACKGROUND-REPEAT: repeat-x
}

.borderGreyVerticalRight {
	BACKGROUND-POSITION: right 50%;
	BACKGROUND-IMAGE: url(${imgdir}/borderGreyLineVertical.gif);
	BACKGROUND-REPEAT: repeat-y
}

.textBlack11pt {
	FONT-WEIGHT: bold;
	FONT-SIZE: 11px;
	COLOR: #000000;
	FONT-FAMILY: Arial, Helvetica, sans-serif
}

.titleBorderEsquerda {
	BACKGROUND-POSITION: left top;
	BACKGROUND-IMAGE: url(${imgdir}/barraTituloCantoEsquerdo.jpg);
	BACKGROUND-REPEAT: no-repeat
}

.titleBorderDireita {
	BACKGROUND-IMAGE: url(${imgdir}/barraTituloCantoDireito.jpg)
}

.titleBorderTop {
	BACKGROUND-IMAGE: url(${imgdir}/barra-top-bottom.jpg);
	BACKGROUND-REPEAT: repeat-x
}

.titleBorderBottom {
	BACKGROUND-IMAGE: url(${imgdir}/barra-top-bottom.jpg);
	BACKGROUND-REPEAT: repeat-x
}

.titleLinasHorizontais {
	BACKGROUND-IMAGE: url(${imgdir}/barraTituloLinhasHorizontais.jpg);
	BACKGROUND-REPEAT: repeat-x
}
</STYLE>