package com.sinfic.ipdms.integration.drools;

import com.sinfic.ipdms.domain.entity.ServicoOnline;
import com.sinfic.ipdms.domain.entity.ColaboradorInfo;
import com.sinfic.ipdms.domain.entity.ColOrganicaFuncao;
import com.sinfic.ipdms.domain.entity.Organica;
//import com.sinfic.ipdms.domain.entity.SoLog;
import com.sinfic.ipdms.comum.rules.result.ObjectResult;
import com.sinfic.ipdms.domain.business.rules.ServicoOnlineAccessContextSupport;
import com.sinfic.ipdms.domain.entity.PermissaoEnum;

rule "Is user the creator of ServicoOnline (nivel 1, 2)"
when
	$result : ObjectResult(value == false) //If the user is not granted yet
	$user: ColaboradorInfo()
	ServicoOnlineAccessContextSupport( variante.processo.permissao == PermissaoEnum.NIVEL0 ||
									   variante.processo.permissao == PermissaoEnum.NIVEL1)
	
	ServicoOnline(creator.login == $user.login)
then
	System.out.println("Rule: Is user the creator of ServicoOnline (nivel 1, 2) Result: Yes!");
	modify($result) {setValue(true)}
end


rule "(DELEGATED) Is user the creator of ServicoOnline (nivel 1, 2)"
when
	$result : ObjectResult(value == false) //If the user is not granted yet
	
	ServicoOnlineAccessContextSupport( variante.processo.permissao == PermissaoEnum.NIVEL0 ||
									   variante.processo.permissao == PermissaoEnum.NIVEL1)
	$context : ServicoOnlineAccessContextSupport()
	ServicoOnline($socreatorlogin : creator.login)
	exists(ColaboradorInfo(login == $socreatorlogin) from $context.delegated)
then
	System.out.println("Rule: (DELEGATED)Is user the creator of ServicoOnline (nivel 1, 2) Result: Yes!");
	modify($result) {setValue(true)}
end

rule "Has organica funcao permissions (nivel 0, nivel 1)"
when
	$result : ObjectResult(value == false) //If the user is not granted yet

	$user: ColaboradorInfo()
	$contextSupport : ServicoOnlineAccessContextSupport()
	ServicoOnlineAccessContextSupport( variante.processo.permissao == PermissaoEnum.NIVEL0 ||
										variante.processo.permissao == PermissaoEnum.NIVEL1)	
	exists(ColOrganicaFuncao(organicaFuncao.organica == $contextSupport.processo.organicaPrincipal) from $user.permissoesColaborador)	
then
	System.out.println("Rule: Has organica funcao permissions (nivel 0, nivel 1) Result: Yes!");
	modify($result) {setValue(true)}
end

rule "(DELEGATED) Has organica funcao permissions (nivel 0, nivel 1)"
when
	$result : ObjectResult(value == false) //If the user is not granted yet

	ServicoOnlineAccessContextSupport($delegated : delegated)
	ServicoOnlineAccessContextSupport($organicaPrincipal : processo.organicaPrincipal)
	$cols : ColaboradorInfo() from $delegated
	$permissoes : ColOrganicaFuncao() from $cols.permissoesColaborador

	ServicoOnlineAccessContextSupport( variante.processo.permissao == PermissaoEnum.NIVEL0 ||
										variante.processo.permissao == PermissaoEnum.NIVEL1)	
	
	exists(ColOrganicaFuncao(organicaFuncao.organica == $organicaPrincipal) from $permissoes)
then
	System.out.println("Rule: (DELEGATED) Has organica funcao permissions (nivel 0, nivel 1) Result: Yes!");
	modify($result) {setValue(true)}
end


rule "Can user tramitar the process (all levels)?"
when
	$result : ObjectResult(value == false) //If the user is not granted yet
	$user: ColaboradorInfo()	
	$contextSupport : ServicoOnlineAccessContextSupport()
	
	exists(ColaboradorInfo(login == $user.login) from $contextSupport.tramitacaoValidUsers)
then
	System.out.println("Rule: Can user tramitar the process (all levels)? Result: Yes!");
	modify($result) {setValue(true)}
end

rule "(DELEGATED) Can user tramitar the process (all levels)?"
when
	$result : ObjectResult(value == false) //If the user is not granted yet
	
	ServicoOnlineAccessContextSupport($whocantramitar : tramitacaoValidUsers)
	ServicoOnlineAccessContextSupport($delegated : delegated)
	$delegatedcol : ColaboradorInfo() from $delegated
	
	exists(ColaboradorInfo(login == $delegatedcol.login) from $whocantramitar)
then
	System.out.println("Rule: (DELEGATED) Can user tramitar the process (all levels)? Result: Yes!");
	modify($result) {setValue(true)}
end



/*rule "Check if user can tramitar the Parent process?"
when
	ObjectResult(value == Boolean.FALSE) //If the user is not granted yet
	$result: ObjectResult()
	$user: ColaboradorInfo()	
	$contextSupport : ServicoOnlineAccessContextSupport()
	exists(ColaboradorInfo(this == $user) from $contextSupport.tramitacaoParentValidUsers)
then
	System.out.println("Utilizador tem permissoes para tramitar processo");
	$result.setValue(Boolean.TRUE);
end

rule "Check if user can tramitar any subprocess?"
when
	ObjectResult(value == Boolean.FALSE) //If the user is not granted yet
	$result: ObjectResult()
	$user: ColaboradorInfo()	
	$contextSupport : ServicoOnlineAccessContextSupport()
	exists(ColaboradorInfo(this == $user) from $contextSupport.tramitacaoSubPorcessesValidUsers)
then
	System.out.println("Utilizador tem permissoes para tramitar processo");
	$result.setValue(Boolean.TRUE);
end*/

rule "Is user Superior Hierarquico (O. P.) de quem instruiu o processo (Nivel 1, 2)"
when
	$result : ObjectResult(value == false) //If the user is not granted yet

	$user: ColaboradorInfo()
	$contextSupport : ServicoOnlineAccessContextSupport()	
	ServicoOnlineAccessContextSupport( variante.processo.permissao == PermissaoEnum.NIVEL0 ||
										variante.processo.permissao == PermissaoEnum.NIVEL1)
	exists(ColaboradorInfo(login == $user.login) from $contextSupport.superioresHierarquicos)
then
	System.out.println("Rule: Is user Superior Hierarquico (O. P.) de quem instruiu o processo (Nivel 1, 2) Result: Yes!");
	modify($result) {setValue(true)}
end


rule "(DELEGATED) Is user Superior Hierarquico (O. P.) de quem instruiu o processo (Nivel 1, 2)"
when
	$result : ObjectResult(value == false) //If the user is not granted yet

	ServicoOnlineAccessContextSupport( variante.processo.permissao == PermissaoEnum.NIVEL0 ||
										variante.processo.permissao == PermissaoEnum.NIVEL1)
	
	ServicoOnlineAccessContextSupport($superiores : superioresHierarquicos)
	ServicoOnlineAccessContextSupport($delegated : delegated)
	$delegatedcol : ColaboradorInfo() from $delegated
	
	exists(ColaboradorInfo(login == $delegatedcol.login) from $superiores)								
then
	System.out.println("Rule: (DELEGATED) Is user Superior Hierarquico (O. P.) de quem instruiu o processo (Nivel 1, 2) Result: Yes!");
	modify($result) {setValue(true)}
end

rule "If user is Superior Hierarquico of who can tramitar process (all levels)?"
when
	$result : ObjectResult(value == false) //If the user is not granted yet
	
	$user: ColaboradorInfo()	
	$contextSupport : ServicoOnlineAccessContextSupport()
	exists(ColaboradorInfo(login == $user.login) from $contextSupport.superioresHierarquicosTramitacao)
then
	System.out.println("Rule: If user is Superior Hierarquico of who can tramitar process (all levels)? Result: Yes!");
	modify($result) {setValue(true)}
end

rule "(DELEGATE) If user is Superior Hierarquico of who can tramitar process (all levels)?"
when
	$result : ObjectResult(value == false) //If the user is not granted yet
	
	ServicoOnlineAccessContextSupport($superiores : superioresHierarquicosTramitacao)
	ServicoOnlineAccessContextSupport($delegated : delegated)
	$delegatedcol : ColaboradorInfo() from $delegated
	
	exists(ColaboradorInfo(login == $delegatedcol.login) from $superiores)
then
	System.out.println("Rule: (DELEGATE) If user is Superior Hierarquico of who can tramitar process (all levels)? Result: Yes!");
	modify($result) {setValue(true)}
end

